import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  '/categories/backend/nodejs/': [
    { text: '学习指南', link: 'index' },
    { text: '核心概念', link: 'core-concepts' },
    { text: '基础语法', link: 'basic-syntax' },
    { text: '常用模块', link: 'common-modules' },
    { text: '异步编程模型', link: 'async-programming' },
    { text: '性能优化', link: 'performance-optimization' },
    { text: '错误处理', link: 'error-handling' },
    { text: '生态系统', link: 'ecosystem' },
    { text: '最佳实践', link: 'best-practices' },
    { text: 'Express框架', children: [
      { text: '学习指南', link: 'express/index' },
      { text: '核心概念', link: 'express/core-concepts' },
      { text: '快速入门', link: 'express/quick-start' },
      { text: '路由系统', link: 'express/routing' },
      { text: '中间件', link: 'express/middleware' },
      { text: '请求与响应处理', link: 'express/request-response' },
      { text: '错误处理', link: 'express/error-handling' },
      { text: '数据库集成', link: 'express/database-integration' },
      { text: '身份验证与授权', link: 'express/authentication' },
      { text: '最佳实践', link: 'express/best-practices' },
      { text: '常见问题', link: 'express/common-issues' },
    ]},
  ],
  '/categories/backend/php/': [
    { text: '学习指南', link: 'index' },
    { text: '基础语法', link: 'basic-syntax' },
    { text: '面向对象编程', link: 'oop' },
    { text: '数组与字符串', link: 'arrays-and-strings' },
    { text: '文件处理', link: 'file-handling' },
    { text: '错误处理', link: 'error-handling' },
    { text: '数据库操作', link: 'database' },
    { text: 'ThinkPHP框架', children: [
      { text: '学习指南', link: 'thinkphp/index' },
      { text: '快速入门', link: 'thinkphp/quick-start' },
      { text: '核心概念', link: 'thinkphp/core-concepts' },
      { text: '数据库操作', link: 'thinkphp/database' },
      { text: '模板引擎', link: 'thinkphp/template-engine' },
      { text: '表单验证', link: 'thinkphp/form-validation' },
    ]},
  ],
  '/categories/backend/java/': [
    { text: '学习指南', link: 'index' },
    { text: '语言基础', link: 'language-basics' },
    { text: '基本数据类型', link: 'primitive-types' },
    { text: '核心语法', link: 'core-syntax' },
    { text: '控制流语句', link: 'control-flow' },
    { text: '面向对象特性', link: 'oop-features' },
    { text: '面向对象编程', link: 'object-oriented' },
    { text: '包', link: 'packages' },
    { text: '常用类库', link: 'common-libraries' },
    { text: '异常处理', link: 'exception-handling' },
    { text: '多线程编程', link: 'multithreading' },
    { text: '集合框架', link: 'collection-framework' },
    { text: 'I/O操作', link: 'io-operations' },
    { text: 'NIO', link: 'NIO' },
    { text: '网络编程', link: 'network-programming' },
    { text: '泛型', link: 'generics' },
    { text: '注解', link: 'annotations' },
    { text: '反射', link: 'reflection' },
    { text: 'Lambda表达式', link: 'lambda-expressions' },
    { text: 'Stream API', link: 'stream-api' },
    { text: 'Spring Boot', children: [
      { text: '入门教程', link: 'spring-boot/getting-started' },
      { text: '配置管理', link: 'spring-boot/configuration' },
      { text: '自动装配', link: 'spring-boot/auto-configuration' },
      { text: 'Web开发', link: 'spring-boot/web-development' },
    ]},
    { text: 'Spring Cloud', children: [
      { text: '入门教程', link: 'spring-cloud/getting-started' },
      { text: '服务注册与发现', link: 'spring-cloud/service-registry' },
      { text: '配置中心', link: 'spring-cloud/configuration-center' },
    ]},
  ],
  '/categories/harmony/': [
      { text: '鸿蒙开发简介', link: 'harmony-intro' },
      { text: '开发环境搭建', link: 'environment-setup' },
      { text: '核心概念', link: 'core-concepts' },
      { text: '基础API使用', link: 'basic-api' },
      { text: '实战案例分析', link: 'practical-cases' },
  ],

  "/categories/miniprogram/": [
    { text: "原生小程序开发", children: [
      { text: "开发前准备", link: "native/preparation" },
      { text: "项目结构详解", link: "native/project-structure" },
      { text: "基础语法精讲", link: "native/basic-syntax" },
      { text: "基础组件使用", link: "native/basic-components" },
      { text: "页面路由与导航", link: "native/page-routing" },
      { text: "数据请求与处理", link: "native/data-request" },
      { text: "状态管理", link: "native/state-management" },
      { text: "组件通信", link: "native/component-communication" },
      { text: "实战案例", link: "native/practical-cases" },
    ]},
    { text: "UniApp跨平台开发", children: [
      { text: "UniApp简介与环境搭建", link: "uniapp/uniapp-intro" },
      { text: "项目结构详解", link: "uniapp/project-structure" },
      { text: "基础语法精讲", link: "uniapp/basic-syntax" },
      { text: "组件使用", link: "uniapp/components" },
      { text: "页面路由与导航", link: "uniapp/page-routing" },
      { text: "数据请求与处理", link: "uniapp/data-request" },
      { text: "状态管理", link: "uniapp/state-management" },
      { text: "跨平台适配", link: "uniapp/cross-platform-adaptation" },
      { text: "性能优化", link: "uniapp/optimization" },
      { text: "实战案例", link: "uniapp/practical-cases" },
    ]},
    { text: "常见问题解决方案", link: "common-problems" },
  ],

  "/categories/frontend/html/": [
    { text: "HTML", icon: "vscode-icons:file-type-html", link: "html/" },
  ],
  "/categories/frontend/css/": [
    { text: "学习指南", link: "index" },
    { text: "CSS 简介", link: "intro" },
    { text: "单位和值", link: "units-and-values" },
    { text: "选择器", link: "selectors-advanced" },
    { text: "伪元素", link: "pseudo-elements" },
    { text: "盒模型", link: "box-model" },
    { text: "布局模式", link: "layout-models" },
    { text: "颜色与字体", link: "color-and-typography" },
    { text: "背景", link: "background" },
    { text: "动画", link: "animation" },
    { text: "圆角、阴影和边框", link: "borders-shadows" },
    { text: "Transform", link: "transform" },
    { text: "Flexbox", link: "flexbox" },
    { text: "Grid 布局", link: "grid" },
    { text: "CSS 变量", link: "variables" },
    { text: "字体和图标", link: "font-and-icons" },
    { text: "容器查询", link: "container-queries" },
    { text: "形状与遮罩", link: "shapes-and-masks" },
    { text: "滤镜与特效", link: "filters-and-effects" },
    { text: "媒体特性", link: "media-features-accessibility" },
    { text: "响应式设计", link: "responsive-design" },
    { text: "渲染性能", link: "rendering-performance" },
    { text: "自定义属性类型注册", link: "custom-property-registration" },
    { text: "函数补充", link: "function-reference" },
  ],
  "/categories/frontend/javascript/": [
    { text: "学习指南", link: "index" },
    { text: "变量与数据类型", link: "variables-and-data-types" },
    { text: "运算符与流程控制", link: "operators-and-control-flow" },
    { text: "函数", link: "function" },
    { text: "对象", link: "object" },
    { text: "数组", link: "array" },
    { text: "原型与原型链", link: "prototype-and-prototype-chain" },
    { text: "闭包", link: "closure" },
    { text: "作用域", link: "scope" },
    { text: "this关键字", link: "this-keyword" },
    { text: "事件循环与回调", link: "event-loop-and-callback" },
    { text: "JSON对象", link: "json" },
    { text: "BOM", link: "bom" },
    { text: "DOM", link: "dom" },
    { text: "let、const与块级作用域", link: "es6-let-const" },
    { text: "解构赋值", link: "es6-destructuring" },
    { text: "模板字符串", link: "es6-template-literals" },
    { text: "字符串的扩展", link: "es6-string-extensions" },
    { text: "正则的扩展", link: "es6-regex-extensions" },
    { text: "数值的扩展", link: "es6-number-extensions" },
    { text: "数组的扩展", link: "es6-array-extensions" },
    { text: "箭头函数", link: "es6-arrow-functions" },
    { text: "函数的扩展", link: "es6-function-extensions" },
    { text: "对象的扩展", link: "es6-object-extensions" },
    { text: "Symbol", link: "es6-symbol" },
    { text: "类与继承", link: "es6-classes" },
    { text: "Promise", link: "es6-promise" },
    { text: "async/await", link: "es6-async-await" },
    { text: "模块化", link: "es6-module" },
    { text: "Set和Map数据结构", link: "es6-set-map" },
    { text: "Iterator 和 for...of 循环", link: "es6-iterator" },
    { text: "Generator 函数", link: "es6-generator" },
    { text: "Proxy", link: "es6-proxy" },
    { text: "Reflect", link: "es6-reflect" },
    { text: "装饰器", link: "es6-decorator" },
  ],
  "/categories/frontend/typescript/": [
    { text: "学习指南", link: "index" },
    { text: "入门概念", link: "intro" },
    { text: "安装配置", link: "installation" },
    { text: "基本类型", link: "basic-types" },
    { text: "函数", link: "functions" },
    { text: "接口与类型别名", link: "interfaces-and-type-aliases" },
    { text: "类与继承", link: "classes-and-inheritance" },
    { text: "泛型", link: "generics" },
    { text: "枚举", link: "enums" },
    { text: "联合类型与交叉类型", link: "union-and-intersection-types" },
    { text: "高级类型", link: "advanced-types" },
    { text: "装饰器", link: "decorators" },
    { text: "模块与命名空间", link: "modules-and-namespaces" },
    { text: "类型声明文件", link: "type-declaration-files" },
    { text: "高级编译选项", link: "advanced-compiler-options" },
    { text: "React 与 TypeScript", link: "react-with-typescript" },
    { text: "Vue 与 TypeScript", link: "vue-with-typescript" },
  ],
  "/categories/frontend/vue2/": [
    { text: "学习指南", link: "index" },
    { text: "基本概念", link: "basics" },
    { text: "组件开发", link: "components" },
    { text: "响应式系统", link: "reactivity" },
    { text: "选项式API", link: "options-api" },
    { text: "常用API", link: "apis" },
    { text: "高级特性", link: "advanced" },
    { text: "实战项目", link: "project" },
  ],
  "/categories/frontend/webpack/": [
    { text: "学习指南", link: "index" },
    { text: "核心概念", link: "core-concepts" },
    { text: "基础配置", link: "basic-configuration" },
    { text: "加载器使用", link: "loaders" },
    { text: "插件配置", link: "plugins" },
    { text: "开发服务器搭建", link: "development-server" },
    { text: "实际应用案例", link: "practical-examples" },
    { text: "性能优化", link: "performance-optimization" },
    { text: "环境变量配置", link: "environment-variables" },
    { text: "Webpack 5新特性", link: "webpack5-features" },
    { text: "构建分析与优化", link: "build-analysis" },
  ],
  "/categories/frontend/network/": [
    { text: "学习指南", link: "index" },
    { text: "网络基础", link: "basics" },
    { text: "API调用", link: "api-calls" },
    { text: "跨域问题", link: "cors" },
    { text: "错误处理", link: "error-handling" },
    { text: "性能优化", link: "performance" },
    { text: "网络安全", link: "security" },
  ],
  "/categories/frontend/vue3/": [
    { text: "学习指南", link: "index" },
    { text: "基本概念", link: "basics" },
    { text: "组件开发", link: "components" },
    { text: "响应式系统", link: "reactivity" },
    { text: "组合式API", link: "composition-api" },
    { text: "常用API", link: "apis" },
    { text: "高级特性", link: "advanced" },
    { text: "实战项目", link: "project" },
    { text: "Vue 2 与 Vue 3 对比", link: "vue-comparison" },
  ],
});
